Resolve errors from missing json objects in API
sul-dlss/wasapi-downloader pull request #113
Opened 2017-06-14 11:56 UTC by ruebot

* Adds `crawl-time` to files object
* Adds `request-url` to response object

Supersedes https://github.com/sul-dlss/wasapi-downloader/pull/112

2017-06-20 17:32 UTC, ndushay requested changes
Hi Nick,

Two choices here, assuming you're okay with my suggestions:

1.  you can tweak your PR per my suggestions
2.  I can merge this as is and do a local PR for the tweaks.

I'm also going to tag a couple colleagues and get them to review this PR as well.

2017-06-20 17:32 UTC, ndushay commented on src/edu/stanford/dlss/was/WasapiFile.java
> +@SuppressWarnings({"checkstyle:LineLength", "checkstyle:MethodCount", "checkstyle:MethodLength"})
I believe it would be better to add the suppress warning for method length for the one method needing it, so roughly line 106 or so

2017-06-20 17:32 UTC, ndushay commented on src/edu/stanford/dlss/was/WasapiFile.java
> +  private String crawlTimeDateStr;
I believe we were using the `DateStr` suffix to clarify what `crawl-start` meant;  would it be clearer to have this be `fileCrawlDateStr` or something like that?

"Time the original content of the file was crawled" is the definition per https://github.com/WASAPI-Community/data-transfer-apis/blob/master/ait-implementation/wasapi/implemented-swagger.yaml#L177-L180

2017-06-20 18:47 UTC, jmartin-sul reviewed
agreed w/ @ndushay on the checkstyle comment.  i don't think i have an opinion one way or the other on the `DateStr` comment, fine w/ the way it is, though i can see how the suggestion might be a bit clearer?

everything else looks good to me.

2017-06-20 22:44 UTC, ndushay commented
@ruebot Nick, I'll merge and then make a separate PR just to get it moving.

2017-06-20 22:45 UTC, merged

2017-06-21 01:22 UTC, ndushay commented
nah - thank YOU for doing this work for us.