set up project skeleton, gradle, travis
sul-dlss/wasapi-downloader pull request #12
Opened 2017-05-01 22:19 UTC by ndushay

2017-05-01 22:51 UTC, ndushay commented
Note that 67% coverage refers to 2 out of 3 lines of code that coveralls is counting, one of which is a class declaration and one of which is a closing brace!

2017-05-02 00:04 UTC, tingulfsen requested changes

2017-05-02 00:04 UTC, tingulfsen commented on src/edu/stanford/dlss/WasapiDownloader.java
> +package edu.stanford.dlss;
Can we create a web archiving package? E.g. src.edu.stanford.dlss.webarchiving or something like that? Like we did with edu.stanford.dlss.wowza for embed.

2017-05-02 00:04 UTC, tingulfsen commented on .travis.yml
> +  - openjdk7
Did we check with LOCKSS that OpenJDK and Java version 7 is the best choice?

2017-05-02 00:16 UTC, ndushay commented on .travis.yml
> +  - openjdk7
OpenJDK 7  is what is currently on was-downloader, and I had the impression that was going to be the java installed on the new VMs.

2017-05-02 00:16 UTC, ndushay commented on src/edu/stanford/dlss/WasapiDownloader.java
> +package edu.stanford.dlss;
sure, can do.

2017-05-02 00:54 UTC, ndushay commented
changed package name to `edu.stanford.dlss.was` as requested.

2017-05-02 17:32 UTC, tingulfsen approved these changes

2017-05-02 17:32 UTC, merged