args override settings, output directory setting
sul-dlss/wasapi-downloader pull request #56
Opened 2017-05-17 22:15 UTC by jmartin-sul

* allow any setting to come from either the command-line args or the .properties file.  if a setting is specified in both, the value from the arg should be used.
* add a setting for the output directory (where the downloaded WARC files go).

closes #54
closes #35

2017-05-17 23:09 UTC, ndushay requested changes
This looks fine.  A couple of minor questions.  Marking as "request changes" largely because this should be rebased on master after #55 gets merged.

2017-05-17 23:09 UTC, ndushay commented on config/settings.properties
> +outputDir=/var/downloadedWarcFiles
I presume there is also a PR in to do this in shared_configs project, or at least an issue for it?

2017-05-17 23:09 UTC, ndushay commented on src/edu/stanford/dlss/was/WasapiDownloaderSettings.java
> +  public static final String OUTPUT_DIR_PARAM_NAME = "outputDir";
this is fine;  just wondering if we want to call out that it's more of an outputBASEdir.  Don't have strong feelings about changing it.

2017-05-18 01:59 UTC, jmartin-sul commented on config/settings.properties
> +outputDir=/var/downloadedWarcFiles
good point, will file an issue

2017-05-18 01:59 UTC, jmartin-sul commented on src/edu/stanford/dlss/was/WasapiDownloaderSettings.java
> +  public static final String OUTPUT_DIR_PARAM_NAME = "outputDir";
renamed to outputBaseDir

2017-05-18 02:03 UTC, jmartin-sul commented on config/settings.properties
> +outputDir=/var/downloadedWarcFiles
https://github.com/sul-dlss/web-archiving/issues/47

2017-05-18 05:13 UTC, ndushay approved these changes

2017-05-18 17:27 UTC, tingulfsen approved these changes

2017-05-18 17:27 UTC, merged