[WIP} get all the result pages
sul-dlss/wasapi-downloader pull request #96
Opened 2017-05-27 00:34 UTC by jmartin-sul

the new `WasapiCrawlSelector(List<WasapiResponse> respList)` constructor still needs some testing

2017-05-27 18:48 UTC, jmartin-sul commented
bonus:  just to see what would happen, i checked out @ndushay's WIP `download-works` branch, and on my laptop i rebased it on this branch, and it applied with no human intervention.  so it looks like it shouldn't be too hard to get both of those chunks of work merged, assuming our respective PRs don't look radically different after review.

2017-05-30 17:51 UTC, tingulfsen approved these changes
👍

2017-05-30 18:17 UTC, ndushay requested changes
Excellent approach!   I would like one more test added, o.w. 👍

2017-05-30 18:17 UTC, ndushay commented on test/edu/stanford/dlss/was/TestWasapiConnection.java
> +
This looks good.  I would also like to see a test that is trying for a pagedJsonQuery, but it only returns a single page.  There is a fixture with that characteristic, fwiw.

Wondering also about a paged query request that returns no results (not that we tested that before ... and maybe that's not part of connection testing ...)

2017-05-31 00:06 UTC, jmartin-sul commented on test/edu/stanford/dlss/was/TestWasapiConnection.java
> +
added tests for a null `jsonQuery` result (and refactored slightly to have `jsonQuery` handle that situation more gracefully itself, which didn't break any of the existing tests, but also added a test for that specific scenario, see new first commit on this branch).  also added a test for a single page result for `pagedJsonQuery`.

2017-05-31 00:06 UTC, jmartin-sul commented on test/edu/stanford/dlss/was/TestWasapiConnection.java
> +
also, i didn't use any fixtures, since this chunk of work all seemed to be one or two levels above the actual JSON parsing.

2017-05-31 18:25 UTC, ndushay requested changes
two very minor questions/quibbles ...

2017-05-31 18:25 UTC, ndushay commented on src/edu/stanford/dlss/was/WasapiConnection.java
> +   * @return null if requestURL is null (as a nicety to callers that might just page through responses' "next" links)
if we're looking for terser prose, this comment might be

```
 @return null when requestURL is null (for callers that just page through responses' "next" links)
```

2017-05-31 18:25 UTC, ndushay commented on src/edu/stanford/dlss/was/WasapiCrawlSelector.java
> +  protected Map<Integer, List<WasapiFile>> crawlIdToFiles = new HashMap<Integer, List<WasapiFile>>();
I'm all for appropriate visibility ... but curious:  why "protected"?  would "package" work?

2017-05-31 18:29 UTC, jmartin-sul commented on src/edu/stanford/dlss/was/WasapiCrawlSelector.java
> +  protected Map<Integer, List<WasapiFile>> crawlIdToFiles = new HashMap<Integer, List<WasapiFile>>();
i had vague thoughts about leaving things open for extension... seems like the sort of thing a subclass might want access to?  i don't feel strongly about it.

2017-05-31 18:47 UTC, merged